#spring.datasource.url=jdbc:mysql://studentinfo.ct4oyss4o1dy.ap-southeast-2.rds.amazonaws.com:3306/studentinfo
#spring.datasource.username=root
#spring.datasource.password=12102003
#Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://dpg-cqm7cljqf0us73a6j9u0-a.singapore-postgres.render.com:5432/studentinfo_eklq
spring.datasource.username=mit
spring.datasource.password=ncP3jWMizR9WQq57JqSOAQ7Ldwj1JUtF
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.tomcat.accesslog.enabled=true
